### ISSUE TITLE
iPad Bugs - if you can find/fix, Happy Hacktoberfest :) 

### ISSUE THREAD

**Issue by jtkaufman737** [jtkaufman737/jtkaufman737.github.io#1]

**Comment by jtkaufman737** [comment]
If you can find bugs, happy Hacktober fest! Primarily looking at iPad, a phantom bug that hasn't been reproducible

**Comment by marielfrank** [comment]
Hey there! Do you know what sort of bugs are occurring on iPad?

**Comment by jtkaufman737** [comment]
Hi @Marielfrank - believe it was a resizing issue on iPad  1 - haven't been able to find it since. And only discoverable on Safari dev options s'far as I can tell
