### ISSUE TITLE
Need some kind of grid fix for whatever kind of device this is(?) ...

### ISSUE THREAD

**Issue by jtkaufman737** [jtkaufman737/jtkaufman737.github.io#2]
![screen shot 2017-10-04 at 7 26 22 pm](https://user-images.githubusercontent.com/18295492/31204468-efb12d1a-a939-11e7-9855-98ea121a464f.png)

(Friend sent it along.) If anyone knows and can spot the grid issue, I'm in your debt and a happy Hacktoberfest to you

**Comment by gakshat14** [comment]
If you haven't assigned this to anyone else then I would like to work on it and which css framework r u using?

**Comment by littlestar642** [comment]
@jtkaufman737 I would love to work on this issue and ping me if you haven't assigned this to anyone.

**Comment by marielfrank** [comment]
Looks like Firefox on Samsung. Are you looking for one project per line + a hamburger menu?

**Comment by jtkaufman737** [comment]
Hi everyone, appreciated @gakshat14 Go ahead and give it a crack, thanks! @littlestar642  if you or @marielfrank could swing a hamburger menu that is fantastic

**Comment by gakshat14** [comment]
@jtkaufman737 I have created a pull request for the grid fix.

**Comment by gakshat14** [comment]
@jtkaufman737 your website is broken. multiple files missing.
